export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const APP_ADD_NEW_POST = 'ADD_NEW_POST';
export const APP_SAVE_NEW_POST = 'APP_SAVE_NEW_POST';
export const APP_DID_SAVE_NEW_POST = 'APP_DID_SAVE_NEW_POST';
export const APP_EDIT_POST = 'APP_EDIT_POST';
export const APP_DID_EDIT_POST = 'APP_DID_EDIT_POST';
export const APP_SAVE_EDITED_POST = 'APP_SAVE_EDITED_POST';
export const APP_DID_SAVE_EDITED_POST = 'APP_DID_SAVE_EDITED_POST';
export const APP_REMOVE_POST = 'APP_REMOVE_POST';
export const APP_DID_REMOVE_POST = 'APP_DID_REMOVE_POST';
export const APP_TRY_TO_VOTE_ON_POST = 'APP_TRY_TO_VOTE_ON_POST';
export const APP_DID_VOTE_ON_POST = 'APP_DID_VOTE_ON_POST';

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const VOTE_ON_COMMENT = 'VOTE_ON_COMMENT';

export const APP_LOADING = 'APP_LOADING';
export const APP_DID_FETCH_INITIAL_DATA_SUCCESS = 'APP_DID_FETCH_INITIAL_DATA_SUCCESS';
export const APP_DID_FETCH_INITIAL_DATA_ERROR = 'APP_DID_FETCH_INITIAL_DATA_ERROR';
export const APP_LOADED = 'APP_LOADED';

export const APP_FETCH_ALL_REACT_POSTS_CATEGORY = 'APP_FETCH_ALL_REACT_POSTS_CATEGORY';
export const APP_DID_FETCH_ALL_REACT_POSTS_CATEGORIES_SUCCESS =
  'APP_DID_FETCH_ALL_REACT_POSTS_CATEGORIES_SUCCESS';
export const APP_DID_FETCH_ALL_REACT_POSTS_CATEGORIES_ERROR =
  'APP_DID_FETCH_ALL_REACT_POSTS_CATEGORIES_ERROR';
export const APP_FETCH_ALL_REDUX_POSTS_CATEGORY = 'APP_FETCH_ALL_REDUX_POSTS_CATEGORY';
export const APP_DID_FETCH_ALL_REDUX_POSTS_CATEGORY_SUCCESS =
  'APP_DID_FETCH_ALL_REDUX_POSTS_CATEGORY_SUCCESS';
export const APP_DID_FETCH_ALL_REDUX_POSTS_CATEGORY_ERROR =
  'APP_DID_FETCH_ALL_REDUX_POSTS_CATEGORY_ERROR';
export const APP_FETCH_ALL_UDACITY_POSTS_CATEGORY = 'APP_FETCH_ALL_UDACITY_POSTS_CATEGORY';
export const APP_DID_FETCH_ALL_UDACITY_POSTS_CATEGORY_SUCCESS =
  'APP_DID_FETCH_ALL_UDACITY_POSTS_CATEGORY_SUCCESS';
export const APP_DID_FETCH_ALL_UDACITY_POSTS_CATEGORY_ERROR =
  'APP_DID_FETCH_ALL_UDACITY_POSTS_CATEGORY_ERROR';

export const APP_CHECK_CATEGORY = 'APP_CHECK_CATEGORY';

export const APP_SHOW_PROGRESS = 'APP_SHOW_PROGRESS';
export const APP_HIDE_PROGRESS = 'APP_HIDE_PROGRESS';
